### ISSUE TITLE
Please upgrade symfony dependencies to 4.x

### ISSUE THREAD

**Issue by aedart** [webuni/front-matter#1]
Hi

Could you please upgrade your dependencies on this project. At the moment this package is being used by [daux.io](https://github.com/dauxio/daux.io) and I would really like to see it's dependencies upgraded.

Nevertheless, I'm still having issues because of a nested dependency to your project (outside usage of daux.io).

**Comment by hason** [comment]
You can use [1.1.0](https://github.com/webuni/front-matter/releases/tag/1.1.0).
